# Default configuration for the assistant
name: example-assistant

# Audio recording parameters
audio:
  bitrate: 128k
  format: wav

# Whisper model used for transcription
whisper_model: base
# Enable speaker diarization using pyannote.audio
enable_diarization: false

# GPT-4 model used for analysis
analysis_model: gpt-4

# Directory where session data is stored
session_root: sessions

# Flask debug mode
flask_debug: false

# File tracking the current processing status
status_file: status.json
