version: '3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db/postgres
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FERNET_KEY=${FERNET_KEY}
      - API_TOKEN=${API_TOKEN}
  worker:
    build:
      context: .
      target: worker
    volumes:
      - .:/worker
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db/postgres
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FERNET_KEY=${FERNET_KEY}
